server:
  addr: 8080

client:
  addr: localhost:9559

P4InfoPath: k8s_dp/p4info.txt
p4BinPath: k8s_dp/k8s_dp.pb.bin
DeviceId: 1
P4ProgConf: k8s_dp/k8s_dp.conf
HostName: "Node1"
LogLevel: "Info"
EnableServices: 0
EnableRouting: 0
DefaultDevice: 0
