GrpcServer:
  addr: localhost:9559

GnmiServer:
  addr: localhost:9339

P4InfoPath: k8s_dp/p4Info.txt
p4BinPath: k8s_dp/k8s_dp.pb.bin
DeviceId: 1
HostName: "Node1"
# Possible debug levels
#  "Panic"
#  "Fatal"
#  "Error"
#  "Warn"
#  "Info"
#  "Debug" (Default)
#  "Trace"
LogLevel: "Debug"
