Infrap4dGrpcServer:
  addr: localhost:9559
  conn: mtls
Infrap4dGnmiServer:
  addr: localhost:9339
  conn: mtls
InfraManager:
  addr: 127.0.0.1:50002
  arpmac: 00:0f:00:04:03:14
  conn: mtls
  ciphersuites: [TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_AES_256_GCM_SHA384]
InterfaceType: cdq
LogLevel: Debug
DeviceID: 1
DBTicker: 5
